name: Create Debug Build

on:
  push:
    branches:
      - dummy

jobs:

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode google-services.json
        env:
          FIREBASE_DEBUG_SECRET: ${{ secrets.FIREBASE_DEBUG_SECRET }}
        run: |
          mkdir -p app/src/debug
          echo $FIREBASE_DEBUG_SECRET > app/src/debug/google-services.json

      - name: Grant permissions
        run: chmod +x ./gradlew

      - name: Run Unit tests
        run: ./gradlew testDebugUnitTest


  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Decode google-services.json
        env:
          FIREBASE_DEBUG_SECRET: ${{ secrets.FIREBASE_DEBUG_SECRET }}
        run: |
          mkdir -p app/src/debug
          echo $FIREBASE_DEBUG_SECRET > app/src/debug/google-services.json

      - name: Grant permissions
        run: chmod +x ./gradlew

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest

  build_apk:
    needs: [ unit_tests, android_tests ]
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode google-services.json
        env:
          FIREBASE_DEBUG_SECRET: ${{ secrets.FIREBASE_DEBUG_SECRET }}
        run: |
          mkdir -p app/src/debug
          echo $FIREBASE_DEBUG_SECRET > app/src/debug/google-services.json

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

